linters:
  enable-all: true
  disable:
    - golint
    - gochecknoglobals
    - prealloc
    - gofmt
    - lll
    - bodyclose
    - goimports
    - funlen
    - stylecheck
    - wsl
    - gocognit
    - godox
    - goconst # todo