builds:
  -
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386

snapshot:
  name_template: SNAPSHOT