builds:
  -
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - 386
      - amd64
      - arm

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386

archive:
  format: binary

snapshot:
  name_template: SNAPSHOT